# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: rbbt-image 0.1.40 ruby lib

Gem::Specification.new do |s|
  s.name = "rbbt-image".freeze
  s.version = "0.1.40"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Miguel Vazquez".freeze]
  s.date = "2023-03-28"
  s.description = "Builds provision files for docker and Vagrant and helps run them".freeze
  s.email = "miguel.vazquez@cnio.es".freeze
  s.executables = ["build_rbbt_provision_sh.rb".freeze, "run_rbbt_docker.rb".freeze]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "Dockerfile",
    "Vagrantfile",
    "lib/rbbt/docker.rb",
    "share/provision_scripts/Dockerfile.R-packages",
    "share/provision_scripts/R.sh",
    "share/provision_scripts/R_custom.sh",
    "share/provision_scripts/alpine_basic_setup.sh",
    "share/provision_scripts/alpine_extended_setup.sh",
    "share/provision_scripts/alpine_setup.sh",
    "share/provision_scripts/bootstrap.sh",
    "share/provision_scripts/functions.sh",
    "share/provision_scripts/gem.sh",
    "share/provision_scripts/hacks.sh",
    "share/provision_scripts/java.sh",
    "share/provision_scripts/migrate.sh",
    "share/provision_scripts/perl_custom.sh",
    "share/provision_scripts/python.sh",
    "share/provision_scripts/python_custom.sh",
    "share/provision_scripts/ruby_custom.sh",
    "share/provision_scripts/slurm_loopback.sh",
    "share/provision_scripts/tokyocabinet.sh",
    "share/provision_scripts/ubuntu_setup.sh",
    "share/provision_scripts/user.sh",
    "share/provision_scripts/variables.sh"
  ]
  s.homepage = "http://github.com/mikisvaz/rbbt-image".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.4.8".freeze
  s.summary = "Build docker and Vagrant (VM) images".freeze

  s.specification_version = 4

  s.add_runtime_dependency(%q<rbbt-util>.freeze, [">= 0"])
end

